ui: mocha-bdd
browsers:
  - name: ie
    version: 6..latest
  - name: opera
    version: 12..latest
  - name: chrome
    version: latest
  - name: firefox
    version: latest
  - name: safari
    version: latest
scripts:
  - "./node_modules/should/should.js"
